#!/usr/bin/env bash

set -euf -o pipefail

WEBCAM="HD Pro Webcam C920"
DEVICE=$(v4l2-ctl --list-devices |grep -A1 "$WEBCAM" | grep -v "$WEBCAM" | xargs)

MIN_ZOOM=100
MAX_ZOOM=270
ZOOM_STEP=20

show_web_cam() {
  mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video4 --profile=low-latency --untimed --vf=hflip --no-keepaspect-window
}

zoom_in() {
  current_zoom=$(v4l2-ctl --device /dev/video4 --get-ctrl zoom_absolute | grep -oP "zoom_absolute: \K...")

  new_zoom=$((current_zoom + ZOOM_STEP))

  if (( new_zoom > MAX_ZOOM )); then
    new_zoom=$MAX_ZOOM
  fi

  v4l2-ctl --device "$DEVICE" --set-ctrl zoom_absolute="$new_zoom"

  exit
}

zoom_out() {
  current_zoom=$(v4l2-ctl --device /dev/video4 --get-ctrl zoom_absolute | grep -oP "zoom_absolute: \K...")

  new_zoom=$((current_zoom - ZOOM_STEP))

  if (( new_zoom < MIN_ZOOM )); then
    new_zoom=$MIN_ZOOM
  fi

  v4l2-ctl --device "$DEVICE" --set-ctrl zoom_absolute="$new_zoom"

  exit
}

bumper() {
  mpv -fs ~/Videos/bumper.mp4
}

case "$1" in 
  show)
    show_web_cam
    exit 0
    ;;
  zoom_in)
    zoom_in
    exit 0
    ;;
  zoom_out)
    zoom_out
    exit 0
    ;;
  bumper)
    bumper
    exit 0
    ;;
  *)
    echo Sorry, but I don\'t know what "$1" means...
    exit 1
    ;;
esac

# vim: ts=2:sw=2:expandtab:
